AllCops:
  Exclude:
    - 'test/dummy/script/**/*'
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Max: 35.62 # TODO: Lower to 15
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 9 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 22
  Exclude:
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 7

Metrics/PerceivedComplexity:
  Max: 9 # TODO: Lower to 7

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  AllowForAlignment:
    - '='
    - '=>'
    - '||='

Style/UnneededPercentQ:
  Exclude:
    - 'route_translator.gemspec'
